services:

  notification-service:
    build:
      context: ..
      dockerfile: urfu-cake-shop-notification-service/Dockerfile
    container_name: cake-shop-notification-service
    ports:
      - "8080:8080"
    env_file:
      - ./config/notify.env
    networks:
      - cake-shop-network

networks:
  cake-shop-network:
    external: true

